version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

networks:
  app-network:
    driver: bridge
